[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.78.0"
HUGO_THEME = "influencer-hugo"
HUGO_BASEURL = "/"

[context.production.environment]
HUGO_VERSION = "0.78.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
#HUGO_BASEURL = "magnusonedstudio.ch"
# HUGO_RELATIVEURLS = true

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.78.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.78.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.78.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# [build]
# publish = "public"
# # command = "cd exampleSite && hugo --gc --themesDir ../.."

# [build.environment]
# HUGO_VERSION = "0.74.3"
# HUGO_THEME = "repo"
# HUGO_BASEURL = "/"
